"""Canonical pure gameplay contracts for x86QW launch adapters."""

from x86qw_runtime.errors import InstallerError

from .catalogs import KTX_CONTEXT_KEYS, parse_ktx_menu_groups, parse_ktx_modes, parse_local_games
from .models import (
    FrogbotIdentity,
    KtxLaunchOptions,
    KtxMapRequirement,
    KtxMenuGroupSpec,
    KtxModeSpec,
    LocalGameSpec,
)
from .planning import (
    FROGBOT_ADD_WAIT_FRAMES,
    active_ktx_map_requirements,
    frogbot_identity,
    ktx_bot_management_alias_commands,
    ktx_bot_name_binary_settings,
    ktx_bot_name_settings,
    ktx_bot_options_requested,
    ktx_bot_team_sequence,
    ktx_chunked_setup_alias_commands,
    ktx_key_alias_commands,
    ktx_launch_commands,
    ktx_mode_bot_limit,
    ktx_mode_help_alias,
    ktx_mode_roster_description,
    quake_colored_frogbot_bytes,
    quake_colored_frogbot_name,
    quote_console_command,
    requested_frogbot_names,
    required_ktx_map_assets,
    validate_frogbot_name,
    validate_ktx_bot_count,
    without_frogbots,
)

__all__ = (
    "FROGBOT_ADD_WAIT_FRAMES",
    "FrogbotIdentity",
    "InstallerError",
    "KTX_CONTEXT_KEYS",
    "KtxLaunchOptions",
    "KtxMapRequirement",
    "KtxMenuGroupSpec",
    "KtxModeSpec",
    "LocalGameSpec",
    "active_ktx_map_requirements",
    "frogbot_identity",
    "ktx_bot_management_alias_commands",
    "ktx_bot_name_binary_settings",
    "ktx_bot_name_settings",
    "ktx_bot_options_requested",
    "ktx_bot_team_sequence",
    "ktx_chunked_setup_alias_commands",
    "ktx_key_alias_commands",
    "ktx_launch_commands",
    "ktx_mode_bot_limit",
    "ktx_mode_help_alias",
    "ktx_mode_roster_description",
    "parse_ktx_menu_groups",
    "parse_ktx_modes",
    "parse_local_games",
    "quake_colored_frogbot_bytes",
    "quake_colored_frogbot_name",
    "quote_console_command",
    "requested_frogbot_names",
    "required_ktx_map_assets",
    "validate_frogbot_name",
    "validate_ktx_bot_count",
    "without_frogbots",
)
